// <auto-generated />
using System;
using AirportAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AirportAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AirportAPI.Domain.Airport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Airports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "London",
                            Code = "LTN",
                            Name = "London Luton Airport"
                        },
                        new
                        {
                            Id = 2,
                            City = "Munich",
                            Code = "MUC",
                            Name = "Munich Airport"
                        },
                        new
                        {
                            Id = 3,
                            City = "Cluj-Napoca",
                            Code = "CLJ",
                            Name = "Cluj International Airport"
                        });
                });

            modelBuilder.Entity("AirportAPI.Domain.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Carts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = 1
                        });
                });

            modelBuilder.Entity("AirportAPI.Domain.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ShopItemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ShopItemId");

                    b.ToTable("CartItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CartId = 1,
                            Quantity = 2,
                            ShopItemId = 1
                        });
                });

            modelBuilder.Entity("AirportAPI.Domain.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Crina"
                        });
                });

            modelBuilder.Entity("AirportAPI.Domain.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "WizzAir"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Lufthansa"
                        });
                });

            modelBuilder.Entity("AirportAPI.Domain.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Birthday")
                        .HasColumnType("date");

                    b.Property<DateOnly>("HiringDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Birthday = new DateOnly(1990, 5, 12),
                            HiringDate = new DateOnly(2021, 3, 1),
                            Name = "Andrei Popescu",
                            Role = 1,
                            Salary = 12000
                        },
                        new
                        {
                            Id = 2,
                            Birthday = new DateOnly(1995, 9, 20),
                            HiringDate = new DateOnly(2022, 6, 15),
                            Name = "Maria Ionescu",
                            Role = 3,
                            Salary = 7000
                        },
                        new
                        {
                            Id = 3,
                            Birthday = new DateOnly(1988, 11, 3),
                            HiringDate = new DateOnly(2020, 1, 10),
                            Name = "Vlad Georgescu",
                            Role = 2,
                            Salary = 10000
                        },
                        new
                        {
                            Id = 4,
                            Birthday = new DateOnly(1997, 2, 14),
                            HiringDate = new DateOnly(2023, 4, 5),
                            Name = "Elena Dumitrescu",
                            Role = 3,
                            Salary = 6800
                        });
                });

            modelBuilder.Entity("AirportAPI.Domain.EmployeeFlight", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("FlightId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId", "FlightId");

                    b.HasIndex("FlightId");

                    b.ToTable("EmployeeFlights");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            FlightId = 1
                        },
                        new
                        {
                            EmployeeId = 1,
                            FlightId = 2
                        },
                        new
                        {
                            EmployeeId = 1,
                            FlightId = 5
                        },
                        new
                        {
                            EmployeeId = 2,
                            FlightId = 1
                        },
                        new
                        {
                            EmployeeId = 2,
                            FlightId = 2
                        },
                        new
                        {
                            EmployeeId = 2,
                            FlightId = 3
                        },
                        new
                        {
                            EmployeeId = 3,
                            FlightId = 1
                        },
                        new
                        {
                            EmployeeId = 3,
                            FlightId = 3
                        },
                        new
                        {
                            EmployeeId = 3,
                            FlightId = 4
                        },
                        new
                        {
                            EmployeeId = 4,
                            FlightId = 4
                        },
                        new
                        {
                            EmployeeId = 4,
                            FlightId = 5
                        });
                });

            modelBuilder.Entity("AirportAPI.Domain.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GateId")
                        .HasColumnType("int");

                    b.Property<int>("RouteId")
                        .HasColumnType("int");

                    b.Property<int>("RunwayId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GateId");

                    b.HasIndex("RouteId");

                    b.HasIndex("RunwayId");

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2026, 3, 27, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            FlightNumber = "W6 3401",
                            GateId = 1,
                            RouteId = 1,
                            RunwayId = 1
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2026, 3, 27, 13, 40, 0, 0, DateTimeKind.Unspecified),
                            FlightNumber = "W6 3402",
                            GateId = 2,
                            RouteId = 2,
                            RunwayId = 2
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2026, 3, 27, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            FlightNumber = "LH 1671",
                            GateId = 3,
                            RouteId = 3,
                            RunwayId = 3
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2026, 3, 27, 17, 25, 0, 0, DateTimeKind.Unspecified),
                            FlightNumber = "LH 1672",
                            GateId = 4,
                            RouteId = 4,
                            RunwayId = 1
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2026, 3, 28, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            FlightNumber = "W6 3403",
                            GateId = 1,
                            RouteId = 1,
                            RunwayId = 2
                        });
                });

            modelBuilder.Entity("AirportAPI.Domain.Gate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Gates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Gate 1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Gate 2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Gate 3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Gate 4"
                        });
                });

            modelBuilder.Entity("AirportAPI.Domain.Manager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Managers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "marcel@gmail.com",
                            Name = "Marcel",
                            Phone = "4074593789"
                        });
                });

            modelBuilder.Entity("AirportAPI.Domain.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("AirportAPI.Domain.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AirportId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("ArrivalTime")
                        .HasColumnType("time");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("DepartureTime")
                        .HasColumnType("time");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("RecurrenceInterval")
                        .HasColumnType("int");

                    b.Property<string>("RouteType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("AirportId");

                    b.HasIndex("CompanyId");

                    b.ToTable("Routes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AirportId = 1,
                            ArrivalTime = new TimeOnly(10, 45, 0),
                            Capacity = 180,
                            CompanyId = 1,
                            DepartureTime = new TimeOnly(8, 30, 0),
                            EndDate = new DateOnly(2026, 12, 31),
                            RecurrenceInterval = 1,
                            RouteType = "DEP",
                            StartDate = new DateOnly(2026, 3, 1)
                        },
                        new
                        {
                            Id = 2,
                            AirportId = 1,
                            ArrivalTime = new TimeOnly(13, 40, 0),
                            Capacity = 180,
                            CompanyId = 1,
                            DepartureTime = new TimeOnly(11, 30, 0),
                            EndDate = new DateOnly(2026, 12, 31),
                            RecurrenceInterval = 1,
                            RouteType = "ARR",
                            StartDate = new DateOnly(2026, 3, 1)
                        },
                        new
                        {
                            Id = 3,
                            AirportId = 2,
                            ArrivalTime = new TimeOnly(15, 20, 0),
                            Capacity = 160,
                            CompanyId = 2,
                            DepartureTime = new TimeOnly(14, 0, 0),
                            EndDate = new DateOnly(2026, 12, 31),
                            RecurrenceInterval = 2,
                            RouteType = "DEP",
                            StartDate = new DateOnly(2026, 3, 1)
                        },
                        new
                        {
                            Id = 4,
                            AirportId = 2,
                            ArrivalTime = new TimeOnly(17, 25, 0),
                            Capacity = 160,
                            CompanyId = 2,
                            DepartureTime = new TimeOnly(16, 0, 0),
                            EndDate = new DateOnly(2026, 12, 31),
                            RecurrenceInterval = 2,
                            RouteType = "ARR",
                            StartDate = new DateOnly(2026, 3, 1)
                        });
                });

            modelBuilder.Entity("AirportAPI.Domain.Runway", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HandleTime")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Runways");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HandleTime = 15,
                            Name = "Runway A1"
                        },
                        new
                        {
                            Id = 2,
                            HandleTime = 20,
                            Name = "Runway B2"
                        },
                        new
                        {
                            Id = 3,
                            HandleTime = 18,
                            Name = "Runway C3"
                        });
                });

            modelBuilder.Entity("AirportAPI.Domain.Shop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.ToTable("Shops");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ManagerId = 1,
                            Name = "Sky Bites",
                            Type = "Food & Beverage"
                        },
                        new
                        {
                            Id = 2,
                            ManagerId = 1,
                            Name = "Runway Cafe",
                            Type = "Coffee Shop"
                        },
                        new
                        {
                            Id = 3,
                            ManagerId = 1,
                            Name = "Elite Boutique",
                            Type = "Luxury Goods"
                        },
                        new
                        {
                            Id = 4,
                            ManagerId = 1,
                            Name = "FlySmart Store",
                            Type = "Travel Essentials"
                        });
                });

            modelBuilder.Entity("AirportAPI.Domain.ShopItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShopId");

                    b.ToTable("ShopItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Fresh sandwich",
                            Name = "Chicken Sandwich",
                            Photo = "https://images.unsplash.com/photo-1568901346375-23c9450c58cd",
                            Price = 12.5f,
                            Quantity = 98,
                            ShopId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Healthy salad",
                            Name = "Caesar Salad",
                            Photo = "https://images.unsplash.com/photo-1551248429-40975aa4de74",
                            Price = 8f,
                            Quantity = 77,
                            ShopId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Fresh juice",
                            Name = "Orange Juice",
                            Photo = "https://images.unsplash.com/photo-1621506289937-a8e4df240d0b",
                            Price = 5.5f,
                            Quantity = 60,
                            ShopId = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "Strong coffee",
                            Name = "Espresso",
                            Photo = "https://images.unsplash.com/photo-1511920170033-f8396924c348",
                            Price = 3.5f,
                            Quantity = 200,
                            ShopId = 2
                        },
                        new
                        {
                            Id = 5,
                            Description = "Coffee with foam",
                            Name = "Cappuccino",
                            Photo = "https://images.unsplash.com/photo-1509042239860-f550ce710b93",
                            Price = 4.5f,
                            Quantity = 150,
                            ShopId = 2
                        },
                        new
                        {
                            Id = 6,
                            Description = "Smooth milk coffee",
                            Name = "Latte",
                            Photo = "https://images.unsplash.com/photo-1523942839745-7848d0f5c9d1",
                            Price = 6f,
                            Quantity = 100,
                            ShopId = 2
                        },
                        new
                        {
                            Id = 7,
                            Description = "High-end watch",
                            Name = "Luxury Watch",
                            Photo = "https://images.unsplash.com/photo-1523275335684-37898b6baf30",
                            Price = 500f,
                            Quantity = 20,
                            ShopId = 3
                        },
                        new
                        {
                            Id = 8,
                            Description = "Premium leather bag",
                            Name = "Designer Handbag",
                            Photo = "https://images.unsplash.com/photo-1584917865442-de89df76afd3",
                            Price = 1200f,
                            Quantity = 15,
                            ShopId = 3
                        },
                        new
                        {
                            Id = 9,
                            Description = "Stylish sunglasses",
                            Name = "RayBan Sunglasses",
                            Photo = "https://images.unsplash.com/photo-1511499767150-a48a237f0083",
                            Price = 300f,
                            Quantity = 10,
                            ShopId = 3
                        },
                        new
                        {
                            Id = 10,
                            Description = "Travel pillow",
                            Name = "Neck Pillow",
                            Photo = "https://images.unsplash.com/photo-1540497077202-7c8a3999166f",
                            Price = 25f,
                            Quantity = 120,
                            ShopId = 4
                        },
                        new
                        {
                            Id = 11,
                            Description = "Universal plug adapter",
                            Name = "Travel Adapter",
                            Photo = "https://images.unsplash.com/photo-1572635196237-14b3f281503f",
                            Price = 10f,
                            Quantity = 205,
                            ShopId = 4
                        },
                        new
                        {
                            Id = 12,
                            Description = "Portable charger",
                            Name = "Power Bank",
                            Photo = "https://images.unsplash.com/photo-1609592424060-bd0c5b305c91",
                            Price = 15f,
                            Quantity = 90,
                            ShopId = 4
                        });
                });

            modelBuilder.Entity("AirportAPI.Domain.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subcategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Duty Free Shops",
                            Subcategory = "Global Duty Free"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Duty Free Shops",
                            Subcategory = "Sky Bites"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Duty Free Shops",
                            Subcategory = "Runway Cafe"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Duty Free Shops",
                            Subcategory = "Elite Boutique"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Duty Free Shops",
                            Subcategory = "FlySmart Store"
                        });
                });

            modelBuilder.Entity("AirportAPI.Domain.Cart", b =>
                {
                    b.HasOne("AirportAPI.Domain.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("AirportAPI.Domain.CartItem", b =>
                {
                    b.HasOne("AirportAPI.Domain.Cart", null)
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AirportAPI.Domain.ShopItem", "ShopItem")
                        .WithMany()
                        .HasForeignKey("ShopItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShopItem");
                });

            modelBuilder.Entity("AirportAPI.Domain.EmployeeFlight", b =>
                {
                    b.HasOne("AirportAPI.Domain.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AirportAPI.Domain.Flight", "Flight")
                        .WithMany()
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("AirportAPI.Domain.Flight", b =>
                {
                    b.HasOne("AirportAPI.Domain.Gate", "Gate")
                        .WithMany()
                        .HasForeignKey("GateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AirportAPI.Domain.Route", "Route")
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AirportAPI.Domain.Runway", "Runway")
                        .WithMany()
                        .HasForeignKey("RunwayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gate");

                    b.Navigation("Route");

                    b.Navigation("Runway");
                });

            modelBuilder.Entity("AirportAPI.Domain.Reservation", b =>
                {
                    b.HasOne("AirportAPI.Domain.Cart", "ReservationCart")
                        .WithMany()
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReservationCart");
                });

            modelBuilder.Entity("AirportAPI.Domain.Route", b =>
                {
                    b.HasOne("AirportAPI.Domain.Airport", "Airport")
                        .WithMany()
                        .HasForeignKey("AirportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AirportAPI.Domain.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Airport");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("AirportAPI.Domain.Shop", b =>
                {
                    b.HasOne("AirportAPI.Domain.Manager", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("AirportAPI.Domain.ShopItem", b =>
                {
                    b.HasOne("AirportAPI.Domain.Shop", "Shop")
                        .WithMany()
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("AirportAPI.Domain.Cart", b =>
                {
                    b.Navigation("CartItems");
                });
#pragma warning restore 612, 618
        }
    }
}

